### ISSUE TITLE
Client Data runs crash when requiring an OpenGL context higher than vanilla

### ISSUE THREAD

**Issue by ChampionAsh5357** [neoforged/NeoForge#1956]
**Minecraft Version:** Tested 1.21.4

**NeoForge Version:** Tested 24.0+

**Steps to Reproduce:**
1. Set the `openGLVersion` in a `neoforge.mods.toml` to a value or range that does not include the vanilla default (version `3.2`).

```toml
modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="examplemod"
version="1.0.0"
displayName="Example Mod"
description='''Example mod'''

[features.examplemod]
openGLVersion="[4,)"
```

2. Use a run configuration that doesn't open the early window screen with a launch handler that uses `Dist#CLIENT` (e.g. `runClientData`)

3. The game crashes

**Description of issue:** The OpenGL version is updated through the early window control, which sets the highest GL context available on the current machine. This dependency is checked as long as the current side is on the client. For client runs, this is fine as the early window control is enabled by default through the `fml.toml`. However, client data runs do not use the early window control, as there is no need to. Since the client data is considered to be run on the physical client, the feature is also checked, causing a crash to occur.

Basically, `openGLVersion` should only be checked for the client runs and not any data runs.
