### ISSUE TITLE
Mod load ordering has strange behavior

### ISSUE THREAD

**Issue by lonevox** [neoforged/NeoForge#540]
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.79

**Logs:** https://gist.github.com/lonevox/bef945c58a742636a5554cdccb1f4faf

**Steps to Reproduce:**
 1. Add a dependency in `mod.toml` and set `ordering="AFTER"`
 2. Add a breakpoint in both your constructor and the dependencies constructor.
 3. Debug and step through the dependencies constructor. You'll see that before it finishes, the breakpoint in your constructor is skipped as it is called in a different thread.

**Description of issue:**
When setting `ordering="AFTER"` on a dependency, the dependencies constructor doesn't finish before the dependent mods constructor is called. The dependency constructor is always called first, however.
Using `ordering="AFTER"`:
```toml
[[dependencies.greate]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.e,)"
    ordering="AFTER"
    side="BOTH"
```
Showing that the Create constructor doesn't finish before my constructor is called:
![image](https://github.com/neoforged/NeoForge/assets/38600896/ea0cf9b2-3079-4b74-91be-ae7e31376d9e)
When testing, this happened with both Create and GTCEu as dependencies, so this doesn't seem to be an issue with a single mod.
